#!/usr/bin/env bash
# claude-init — Claude context scaffolder
# github.com/jhaksh-24/claude-init
# Usage: claude-init inside any project folder

set -euo pipefail

# ── colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

# ── helpers ──────────────────────────────────────────────────────────────────
info()    { echo -e "${CYAN}→${RESET} $1"; }
success() { echo -e "${GREEN}✓${RESET} $1"; }
warn()    { echo -e "${YELLOW}⚠${RESET} $1"; }
error()   { echo -e "${RED}✗${RESET} $1"; exit 1; }
bold()    { echo -e "${BOLD}$1${RESET}"; }
dim()     { echo -e "${DIM}$1${RESET}"; }

# ── banner ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${CYAN}"
echo "  ██████╗██╗      █████╗ ██╗   ██╗██████╗ ███████╗"
echo " ██╔════╝██║     ██╔══██╗██║   ██║██╔══██╗██╔════╝"
echo " ██║     ██║     ███████║██║   ██║██║  ██║█████╗  "
echo " ██║     ██║     ██╔══██║██║   ██║██║  ██║██╔══╝  "
echo " ╚██████╗███████╗██║  ██║╚██████╔╝██████╔╝███████╗"
echo "  ╚═════╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝"
echo -e "${RESET}"
echo -e "  ${DIM}Claude context scaffolder — zero token waste${RESET}"
echo ""

# ── check prompt.md exists ───────────────────────────────────────────────────
if [ ! -f "prompt.md" ]; then
  warn "No prompt.md found in current directory."
  echo ""
  echo -e "  Create ${BOLD}prompt.md${RESET} first. Write your project idea in plain english."
  echo -e "  ${DIM}Messy is fine. Use Claude/ChatGPT website to refine it, paste result here.${RESET}"
  echo ""
  echo -e "  ${CYAN}Template:${RESET}"
  echo ""
  echo '  ## Project'
  echo '  [what you are building in 2-3 sentences]'
  echo ''
  echo '  ## Stack'
  echo '  [languages, frameworks, databases]'
  echo ''
  echo '  ## Goal'
  echo '  [what done looks like — demo, deployed, tested]'
  echo ''
  echo '  ## Constraints'
  echo '  [time limit, team size, platform restrictions]'
  echo ""
  exit 1
fi

success "Found prompt.md"
echo ""

# ── read prompt.md ────────────────────────────────────────────────────────────
PROMPT_CONTENT=$(cat prompt.md)

# ── extract metadata from prompt.md (simple grep, no API needed) ──────────────
PROJECT_NAME=$(grep -i "^#\|project name\|## project" prompt.md | head -1 | sed 's/[#]*//g' | xargs)
if [ -z "$PROJECT_NAME" ]; then
  PROJECT_NAME=$(basename "$PWD")
fi

# ── confirm before writing ────────────────────────────────────────────────────
bold "Project detected: $PROJECT_NAME"
dim "Will generate .claude/ folder with 6 files"
echo ""
echo -e "  ${CYAN}FILES TO BE CREATED:${RESET}"
echo "  .claude/AGENT.md    — role, conventions, phase structure"
echo "  .claude/STATE.md    — phase tracker (you update this)"
echo "  .claude/RULES.md    — your control points, approval gates"
echo "  .claude/ERRORS.md   — mistake log (fills during project)"
echo "  .claude/MEMORY.md   — locked decisions, never re-debate"
echo "  .claude/CONTEXT.md  — token optimization instructions"
echo ""
read -rp "$(echo -e "${BOLD}Proceed? [y/N]:${RESET} ")" confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
  echo "Aborted."
  exit 0
fi

echo ""

# ── create .claude folder ─────────────────────────────────────────────────────
mkdir -p .claude
success "Created .claude/"

# ── AGENT.md ──────────────────────────────────────────────────────────────────
cat > .claude/AGENT.md << AGENT
# AGENT.md
# Generated by claude-init — edit freely but keep the structure
# Source of truth: prompt.md (your project spec)

---

## YOUR ROLE

You are a senior engineer and architect working on this project.
You are NOT the decision maker — the developer is.
You propose. The developer disposes.

Read this file at the start of every session.
Read STATE.md to know exactly where you are.
Read MEMORY.md before making any architectural decision.
Read ERRORS.md to avoid repeating past mistakes.

---

## PROJECT

$(cat prompt.md)

---

## CODING STANDARDS — NON-NEGOTIABLE

These apply to every file you generate. Violating them is not acceptable.

- Follow conventions already established in the codebase — never introduce a new pattern without flagging it
- Every function must have a comment explaining WHY it exists, not WHAT it does
- Every integration point (API call, DB query, external service) must be marked: \`/// @integration SERVICE_NAME\`
- Use explicit types — never rely on inference where ambiguity exists
- Custom errors over generic throws/panics/exceptions — always descriptive
- Checks before effects before interactions — always
- No magic numbers — name every constant
- No TODO comments in committed code — either build it or don't

---

## PHASE STRUCTURE — CRITICAL

Before starting ANY phase you MUST stop and tell me:
1. What you are about to build (specific files and functions)
2. How you are building it (design decisions)
3. Why that design (tradeoffs considered)
4. Fallbacks (what happens if this component fails)
5. Drawbacks (limitations of your approach)
6. Dependencies (what from prior phases this needs)
7. Questions (anything needing clarification)

**Only proceed after I explicitly say "proceed" or "approved".**
**Never compress phases. Never skip ahead. Never assume approval.**

---

## TOKEN EFFICIENCY RULES — MANDATORY

These rules exist to prevent credit waste. Follow them exactly.

1. **Never re-explain architecture in chat** — it is already in this file
2. **Never generate code I did not ask for** — one task per turn
3. **Never speculate ahead** — only build what the current phase requires
4. **Always read STATE.md first** — never ask me what phase we are on
5. **When you drift, re-read this file** — do not ask me to repeat instructions
6. **Short responses for approvals** — if I say "proceed", just build, no preamble
7. **Flag before you deviate** — if you need to break a rule, ask first

---

## MEMORY PROTOCOL

- Before every response: read STATE.md
- After completing a file: mentally update what changed (I will update STATE.md)
- Before any architectural decision: check MEMORY.md — if it is there, do not re-debate it
- When you find a bug or make a mistake: I will log it in ERRORS.md — check it next session

---

## INTEGRATION ANNOTATIONS

Mark every external connection point in code:
\`\`\`
/// @integration FRONTEND — called via client SDK
/// @integration BACKEND — triggered by API relay  
/// @integration ML_SERVICE — receives model output
/// @integration DB — direct database operation
/// @integration EXTERNAL_API — third party service call
\`\`\`

---

## WHAT I OWN (DEVELOPER — NOT YOU)

- Architecture decisions
- Tech stack choices
- Phase approval
- What gets built and in what order
- When to override your output
- Final review of every file

Do not make these decisions autonomously. Propose and wait.
AGENT

success "Generated AGENT.md"

# ── STATE.md ──────────────────────────────────────────────────────────────────
cat > .claude/STATE.md << STATE
# STATE.md
# Read this FIRST every session. Update after every completed task.
# Developer updates this — not Claude.

---

## CURRENT STATUS

Phase: 0 — NOT STARTED
Last completed: nothing yet
Next task: Phase 1 briefing — Claude proposes, developer approves

---

## PHASE TRACKER

| Phase | Name | Status | Files |
|-------|------|--------|-------|
| 1 | Foundation | ⬜ pending | — |
| 2 | Core | ⬜ pending | — |
| 3 | | ⬜ pending | — |
| 4 | | ⬜ pending | — |
| 5 | | ⬜ pending | — |
| 6 | Integration | ⬜ pending | — |
| 7 | Testing + Deploy | ⬜ pending | — |

> Fill phase names after Claude proposes the roadmap in Phase 0 briefing

---

## FILES WRITTEN THIS SESSION

(update as you go)

---

## LOCKED DECISIONS

> Move decisions here once approved — Claude never re-debates these

---

## BLOCKERS

none

---

## LAST SESSION SUMMARY

(fill at end of each session so next session starts clean)
STATE

success "Generated STATE.md"

# ── RULES.md ──────────────────────────────────────────────────────────────────
cat > .claude/RULES.md << RULES
# RULES.md
# These are the developer's non-negotiables.
# Claude reads this and never violates these without explicit permission.

---

## CONTROL RULES

1. **I approve every phase before you start it** — no exceptions
2. **I approve every architectural decision** — propose, do not decide
3. **I review every file before it is considered complete** — do not mark done without my sign-off
4. **I decide when to override your output** — do not argue, implement my decision
5. **I set the pace** — do not rush ahead because you think the next step is obvious

---

## TECHNICAL NON-NEGOTIABLES

> Fill these with your preferences. Examples below — edit freely.

- No ORM magic — raw queries or explicit query builders only
- No auto-generated migrations without my review
- No external dependencies added without flagging to me first
- No cloud calls in local dev — mock everything
- Security-critical code gets a second look — flag it explicitly

---

## WHAT GOOD OUTPUT LOOKS LIKE

- One file or one function per turn unless I say otherwise
- Code compiles and runs before you call it done
- Tests exist for every non-trivial function
- Every TODO is a blocker — surface it, do not bury it

---

## RED LINES

These are things Claude must NEVER do without explicit permission:

- Delete or overwrite existing files
- Change the database schema
- Modify authentication or security logic autonomously
- Add a new dependency to the project
- Change the deployment configuration
- Skip a phase gate
RULES

success "Generated RULES.md"

# ── MEMORY.md ────────────────────────────────────────────────────────────────
cat > .claude/MEMORY.md << MEMORY
# MEMORY.md
# Locked architectural decisions — never re-debate what is recorded here.
# Developer writes this. Claude reads it before every decision.

---

## FORMAT

\`\`\`
## [DECISION TITLE]
Date: YYYY-MM-DD
Decision: what was decided
Reason: why this was chosen
Alternatives rejected: what else was considered and why it lost
Revisit if: condition under which this can be re-opened
\`\`\`

---

## DECISIONS

(empty — fill as project progresses)

---

## PATTERNS APPROVED

(libraries, abstractions, design patterns locked in for this project)

---

## PATTERNS BANNED

(things tried and rejected — do not suggest these again)
MEMORY

success "Generated MEMORY.md"

# ── ERRORS.md ────────────────────────────────────────────────────────────────
cat > .claude/ERRORS.md << ERRORS
# ERRORS.md
# Every mistake made in this project — so they never repeat.
# Developer writes this. Claude reads it every session.

---

## FORMAT

\`\`\`
## [ERROR TITLE]
Date: YYYY-MM-DD
Phase: X
What happened: description
Why it happened: root cause
Fix applied: what resolved it
Prevention: what rule prevents this next time
\`\`\`

---

## ERRORS

(empty — fills as project progresses)
ERRORS

success "Generated ERRORS.md"

# ── CONTEXT.md ───────────────────────────────────────────────────────────────
cat > .claude/CONTEXT.md << CONTEXT
# CONTEXT.md
# Token optimization protocol — read this to understand how to work efficiently.
# This file exists because context = credits. Every wasted token is real money.

---

## WHY THIS EXISTS

Claude processes the ENTIRE conversation history on every single turn.
A 50-turn chat at 2000 tokens/turn = 100,000 tokens just in context on turn 50.
This file system keeps context FLAT instead of ever-growing.

---

## THE EFFICIENCY HIERARCHY

\`\`\`
Most expensive  →  re-explaining architecture in chat
                →  correction loops from drift
                →  speculative generation
                →  long approval messages
Least expensive →  "proceed"
                →  file reads
                →  short targeted questions
\`\`\`

---

## RULES FOR THE DEVELOPER

1. Keep your messages SHORT — "proceed", "fix X in Y", "approved"
2. NEVER re-explain the stack or architecture in chat — it is in AGENT.md
3. Update STATE.md yourself between phases — do not ask Claude to do it in chat
4. Start new conversations for new phases when context gets heavy
5. If Claude drifts, say "re-read AGENT.md" — not a long correction

---

## RULES FOR CLAUDE

1. Read AGENT.md, STATE.md, MEMORY.md, ERRORS.md at session start
2. Never ask something already answered in these files
3. One task per turn — do not bundle unrequested work
4. Phase briefing = stop and wait — never auto-proceed
5. If context window feels heavy, say so — developer will start a fresh session

---

## SESSION HANDOFF PROTOCOL

At the end of every session:
1. Developer updates STATE.md with what was completed
2. Developer logs any new decisions in MEMORY.md
3. Developer logs any mistakes in ERRORS.md
4. Next session starts with: "read .claude/ and tell me current state"
5. Claude confirms state from files — zero re-explanation needed

---

## THE ONE RULE

**Everything that can live in a file, lives in a file.**
**The chat is only for decisions and approvals.**
CONTEXT

success "Generated CONTEXT.md"

# ── .gitignore entry ──────────────────────────────────────────────────────────
if [ -f ".gitignore" ]; then
  if ! grep -q "\.claude/ERRORS\.md" .gitignore 2>/dev/null; then
    echo "" >> .gitignore
    echo "# claude-init — keep templates, ignore session logs" >> .gitignore
    echo "# .claude/ERRORS.md" >> .gitignore  # commented — user decides
  fi
fi

# ── done ─────────────────────────────────────────────────────────────────────
echo ""
bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
success "claude-init complete"
bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "  ${CYAN}NEXT STEP:${RESET}"
echo ""
echo -e "  Open Claude Code (or Antigravity / OpenRouter)"
echo -e "  Start with this exact message:"
echo ""
echo -e "  ${BOLD}\"Read everything in .claude/ and give me your Phase 1 briefing.\"${RESET}"
echo ""
echo -e "  ${DIM}Claude will propose the full roadmap. You approve before a single line is written.${RESET}"
echo ""
echo -e "  ${CYAN}YOUR FILES:${RESET}"
echo -e "  .claude/AGENT.md    — role + conventions + phase rules"
echo -e "  .claude/STATE.md    — update this yourself between phases"
echo -e "  .claude/RULES.md    — your non-negotiables (edit these)"
echo -e "  .claude/MEMORY.md   — log decisions here as you make them"
echo -e "  .claude/ERRORS.md   — log mistakes here when they happen"
echo -e "  .claude/CONTEXT.md  — token efficiency protocol"
echo ""
dim "  github.com/jhaksh-24/claude-init"
echo ""
