#!/usr/bin/env bash
# claude-init v2.0 — Claude context scaffolder
# Designed by an AI, for AI-assisted development
# github.com/jhaksh-24/claude-init

set -euo pipefail

VERSION="2.0.0"
CLAUDE_DIR=".claude"

# ── colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

# ── helpers ─────────────────────────────────────────────────────────────────
info()    { echo -e "${CYAN}→${RESET} $1"; }
success() { echo -e "${GREEN}✓${RESET} $1"; }
warn()    { echo -e "${YELLOW}⚠${RESET} $1"; }
error()   { echo -e "${RED}✗${RESET} $1"; exit 1; }
bold()    { echo -e "${BOLD}$1${RESET}"; }
dim()     { echo -e "${DIM}$1${RESET}"; }

today() { date +%Y-%m-%d 2>/dev/null || echo "unknown"; }

sed_inplace() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

# ── banner ──────────────────────────────────────────────────────────────────
show_banner() {
  echo ""
  echo -e "${BOLD}${CYAN}"
  echo "  ██████╗██╗      █████╗ ██╗   ██╗██████╗ ███████╗"
  echo " ██╔════╝██║     ██╔══██╗██║   ██║██╔══██╗██╔════╝"
  echo " ██║     ██║     ███████║██║   ██║██║  ██║█████╗  "
  echo " ██║     ██║     ██╔══██║██║   ██║██║  ██║██╔══╝  "
  echo " ╚██████╗███████╗██║  ██║╚██████╔╝██████╔╝███████╗"
  echo "  ╚═════╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝"
  echo -e "${RESET}"
  echo -e "  ${DIM}v${VERSION} — context scaffolder — zero token waste${RESET}"
  echo ""
}

show_banner_mini() {
  echo ""
  echo -e "  ${BOLD}${CYAN}claude-init${RESET} ${DIM}v${VERSION}${RESET}"
  echo ""
}

# ── help ────────────────────────────────────────────────────────────────────
show_help() {
  show_banner_mini
  echo "  USAGE:"
  echo "    claude-init                  Generate .claude/ scaffold"
  echo "    claude-init checkpoint       Update state files interactively"
  echo "    claude-init status           Print current project state"
  echo ""
  echo "  FLAGS:"
  echo "    --minimal, -m    Generate lighter scaffold (4 files)"
  echo "    --force, -f      Overwrite existing .claude/ files"
  echo "    --help, -h       Show this help"
  echo "    --version, -v    Show version"
  echo ""
  echo "  ALIASES:"
  echo "    checkpoint → ck"
  echo "    status     → st"
  echo "    refine     → rf"
  echo ""
}

# ═══════════════════════════════════════════════════════════════════════════
# TEMPLATE GENERATORS
# ═══════════════════════════════════════════════════════════════════════════

generate_agent() {
  local project_name="$1"
  cat > "$CLAUDE_DIR/AGENT.md" << 'AGENT_HEADER'
# AGENT.md — Operating Manual
# Generated by claude-init v2.0 — edit freely, keep the structure

---

## QUICK REFERENCE

AGENT_HEADER

  cat >> "$CLAUDE_DIR/AGENT.md" << AGENT_REF
> **Project:** ${project_name}
> **Phase:** read STATE.md
> **Control:** Claude proposes → Developer approves → then build
AGENT_REF

  cat >> "$CLAUDE_DIR/AGENT.md" << 'AGENT_BODY'

---

## YOUR ROLE

You are a senior engineer working on this project.
You do NOT make decisions — the developer does.
You propose. The developer disposes. Always.

**Session startup (do this EVERY time, silently):**
1. Read STATE.md → know where you are
2. Read MEMORY.md → know what's been decided
3. Read ERRORS.md → know what to avoid
4. Read FILES.md → know what exists and where
5. Confirm state to developer in ≤3 lines

---

## PROJECT SPEC

AGENT_BODY

  cat prompt.md >> "$CLAUDE_DIR/AGENT.md"

  cat >> "$CLAUDE_DIR/AGENT.md" << 'AGENT_REST'

---

## CODING STANDARDS — NON-NEGOTIABLE

These exist because violations create correction loops that waste tokens.

- **Follow existing conventions** — never introduce new patterns silently
- **Comments explain WHY, not WHAT** — "handles race condition in X" not "loops through array"
- **Mark integration points:** `/// @integration SERVICE_NAME`
- **Explicit types** — no ambiguous inference
- **Custom errors** — descriptive, never generic throws/panics
- **CEI pattern** — checks → effects → interactions, always
- **Named constants** — no magic numbers, no magic strings
- **No buried TODOs** — surface as blockers or build it now

---

## PHASE PROTOCOL

Before ANY phase, stop and present this table:

| Item | You must state |
|------|---------------|
| **Building** | exact files and functions |
| **Design** | approach and architecture |
| **Rationale** | tradeoffs you considered |
| **Fallback** | what if this approach fails |
| **Dependencies** | what from prior phases this needs |
| **Questions** | anything unclear — ask now, not mid-build |

**Only proceed after explicit "proceed" or "approved".**
**Never compress phases. Never skip. Never assume approval.**

---

## TOKEN PROTOCOL

These rules prevent credit waste. Follow exactly.

1. Architecture lives in this file — never re-explain in chat
2. One task per turn — never bundle unrequested work
3. Read STATE.md — never ask "where are we?"
4. "proceed" means build immediately — zero preamble
5. Drifting? Re-read this file — don't ask developer to repeat
6. Need to break a rule? Ask first, then break
7. Short responses for approvals — no restating what was just said

---

## OWNERSHIP

```
Developer owns:              You own:
├── architecture              ├── implementation
├── stack choices              ├── boilerplate
├── phase approval             ├── repetitive patterns
├── build order                ├── documentation
├── final review               ├── test generation
└── override authority         └── syntax + conventions
```

Propose and wait. Always.
AGENT_REST
}

generate_state() {
  cat > "$CLAUDE_DIR/STATE.md" << STATE
# STATE.md — Session State
# READ THIS FIRST. EVERY SESSION. NO EXCEPTIONS.
# Developer maintains this. Claude reads it.

---

## META

Last Updated: $(today)
Session Count: 0
Context Health: fresh

---

## CURRENT STATUS

Phase: 0 — NOT STARTED
Last Completed: nothing
Next Task: Claude reads .claude/ and proposes Phase 1 roadmap
Blockers: none

---

## PHASE TRACKER

| # | Phase | Status | Key Files |
|---|-------|--------|-----------|
| 1 | Foundation | ⬜ pending | — |
| 2 | Core | ⬜ pending | — |
| 3 | — | ⬜ pending | — |
| 4 | — | ⬜ pending | — |
| 5 | — | ⬜ pending | — |
| 6 | Integration | ⬜ pending | — |
| 7 | Test + Deploy | ⬜ pending | — |

> Fill phase names after Claude proposes the roadmap in Phase 0

---

## SESSION LOG

> Append after each session (most recent first). Use \`claude-init checkpoint\`.

---

## DECISIONS PENDING

> Things needing developer input before Claude can proceed.

(none)
STATE
}

generate_memory() {
  cat > "$CLAUDE_DIR/MEMORY.md" << 'MEMORY'
# MEMORY.md — Locked Decisions
# If it's here, it's decided. Claude does NOT re-debate.
# Developer writes this. Claude reads before every design choice.

---

## STACK & VERSIONS

> Lock exact versions here. Claude uses these, no substitutions.

```
Language:
Runtime:
Framework:
Database:
ORM/Query:
Auth:
Deploy:
Test:
```

---

## ARCHITECTURAL DECISIONS

> Format for each decision:
>
> ### [TITLE]
> **Date:** YYYY-MM-DD
> **Decision:** what was decided
> **Reason:** why
> **Rejected:** alternatives and why they lost
> **Revisit if:** condition to reopen

(empty — fill as project progresses)

---

## PATTERNS APPROVED

> Libraries, abstractions, and design patterns locked for this project.

(empty)

---

## PATTERNS BANNED

> Tried and rejected — never suggest again.

(empty)

---

## DEPENDENCY DECISIONS

| Dependency | Purpose | Why This One | Date |
|-----------|---------|-------------|------|
| | | | |
MEMORY
}

generate_errors() {
  cat > "$CLAUDE_DIR/ERRORS.md" << 'ERRORS'
# ERRORS.md — Mistake Log & Known Issues
# Claude reads this EVERY session to avoid repeating mistakes.

---

## KNOWN BUGS (UNFIXED)

> Active issues the developer knows about but hasn't fixed yet.
> Claude: be aware of these. Don't trip over them. Don't try to fix unless asked.

(none)

---

## ACTIVE WORKAROUNDS

> Temporary hacks in the codebase. Include the file and line if possible.

(none)

---

## ERROR LOG

> Format for each error:
>
> ### [ERROR TITLE]
> **Date:** YYYY-MM-DD
> **Phase:** X
> **What happened:** description
> **Root cause:** why
> **Fix applied:** what resolved it
> **Prevention rule:** what stops this next time

(empty — fills as project progresses)
ERRORS
}

generate_rules() {
  cat > "$CLAUDE_DIR/RULES.md" << 'RULES'
# RULES.md — Developer's Non-Negotiables
# Claude reads this and never violates without explicit permission.

---

## CONTROL GATES

1. **Phase approval required** — every phase needs explicit "proceed"
2. **Architecture decisions are mine** — propose, don't decide
3. **File review before done** — nothing is complete without my sign-off
4. **I set the pace** — don't rush because the next step seems obvious
5. **My override is final** — implement it, don't argue

---

## TECHNICAL NON-NEGOTIABLES

> Edit these to match your preferences.

- No ORM magic — raw queries or explicit query builders only
- No auto-generated migrations without review
- No new dependencies without flagging first
- No cloud/external calls in local dev — mock everything
- Security-critical code gets explicit flag: `/// @security-review`

---

## OUTPUT STANDARDS

- One file or one function per turn unless told otherwise
- Code must compile/run before declaring done
- Tests for every non-trivial function
- Every TODO is a blocker — surface it, don't bury it

---

## RED LINES — NEVER WITHOUT PERMISSION

- Delete or overwrite existing files
- Change database schema
- Modify auth or security logic
- Add new dependencies
- Change deploy config
- Skip a phase gate
- Refactor code that isn't part of the current task

---

## OVERRIDE PROTOCOL

When the developer says to break a rule:
1. Confirm which rule is being overridden
2. Execute the override
3. Note it in MEMORY.md as an exception
4. Resume normal rules next turn
RULES
}

generate_context() {
  cat > "$CLAUDE_DIR/CONTEXT.md" << 'CONTEXT'
# CONTEXT.md — Token Efficiency Protocol
# Context = credits. Every wasted token is real money.

---

## THE PROBLEM

Claude processes the ENTIRE conversation on every turn.
50 turns × 2000 tokens/turn = 100,000 tokens of context by turn 50.
`.claude/` files keep context FLAT — 6 small files vs. 50 growing turns.

---

## COST HIERARCHY

```
EXPENSIVE    re-explaining architecture in chat
             correction loops from drift
             speculative generation
             long approval messages
CHEAP        "proceed"
             file reads
             short targeted questions
```

---

## RULES FOR DEVELOPER

1. Keep messages short — "proceed", "fix X in Y", "approved"
2. Never re-explain stack in chat — it's in AGENT.md
3. Update STATE.md yourself — use `claude-init checkpoint`
4. Start fresh conversations when context gets heavy
5. Claude drifts? Say "re-read AGENT.md" — not a long correction

---

## RULES FOR CLAUDE

1. Read .claude/ files at session start — silently
2. Never ask what's already answered in these files
3. One task per turn — no bundled surprises
4. Phase briefing = stop and wait — never auto-proceed
5. Context heavy? Say so — developer starts fresh session

---

## SESSION HANDOFF

End of session:
1. Developer runs `claude-init checkpoint`
2. STATE.md, MEMORY.md, ERRORS.md get updated
3. Next session: "read .claude/ and tell me current state"
4. Claude confirms in ≤3 lines — zero re-explanation

---

## THE ONE RULE

**Everything that can live in a file, lives in a file.**
**Chat is only for decisions and approvals.**
CONTEXT
}

generate_files() {
  cat > "$CLAUDE_DIR/FILES.md" << 'FILES'
# FILES.md — Project File Registry
# Update when files are created, renamed, or deleted.
# Claude reads this instead of scanning the filesystem.

---

## DIRECTORY STRUCTURE

```
(update with actual project tree as it develops)
```

---

## FILE REGISTRY

| File | Purpose | Status |
|------|---------|--------|
| prompt.md | Project specification | 🟢 stable |

> Add every file as you create it. Takes 5 seconds. Saves minutes per session.

### Status Key

- 🟢 **stable** — tested and working
- 🟡 **wip** — in progress, may change
- 🔴 **broken** — known issues (see ERRORS.md)
- ⬜ **planned** — not yet created

---

## ENTRY POINTS

- **Main:** (app entry point — e.g. src/main.rs, app.py, index.ts)
- **Config:** (env/config files — e.g. .env, config.toml)
- **Tests:** (test directory — e.g. tests/, __tests__/)
- **Build:** (build scripts — e.g. Makefile, docker-compose.yml)

---

## RECENT CHANGES

> Updated by `claude-init checkpoint`. Most recent first.

(none yet)
FILES
}

# ═══════════════════════════════════════════════════════════════════════════
# COMMANDS
# ═══════════════════════════════════════════════════════════════════════════

cmd_init() {
  local minimal="$1"
  local force="$2"

  show_banner

  # ── check prompt.md ──
  if [ ! -f "prompt.md" ]; then
    warn "No prompt.md found in current directory."
    echo ""
    echo -e "  Create ${BOLD}prompt.md${RESET} first. Describe your project — messy is fine."
    echo -e "  ${DIM}Use Claude.ai or ChatGPT to refine it, paste result here.${RESET}"
    echo ""
    echo -e "  ${CYAN}Quick template:${RESET}"
    echo ""
    echo "  ## Project"
    echo "  [what you're building]"
    echo ""
    echo "  ## Stack"
    echo "  [languages, frameworks, databases]"
    echo ""
    echo "  ## Goal"
    echo "  [what done looks like]"
    echo ""
    exit 1
  fi

  success "Found prompt.md"
  echo ""

  # ── extract project name ──
  local project_name
  project_name=$(grep -i "^#\|project name\|## project" prompt.md | head -1 | sed 's/[#]*//g' | xargs)
  if [ -z "$project_name" ]; then
    project_name=$(basename "$PWD")
  fi

  # ── check existing .claude/ ──
  if [ -d "$CLAUDE_DIR" ] && [ "$force" = "false" ]; then
    warn ".claude/ already exists."
    echo ""
    read -rp "$(echo -e "  ${BOLD}Overwrite? [y/N]:${RESET} ")" overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
      echo "  Aborted. Use --force to skip this prompt."
      exit 0
    fi
    echo ""
  fi

  # ── confirm ──
  bold "Project: $project_name"
  if [ "$minimal" = "true" ]; then
    dim "Mode: minimal (4 files)"
  else
    dim "Mode: full (7 files)"
  fi
  echo ""

  local file_list
  if [ "$minimal" = "true" ]; then
    file_list="AGENT.md STATE.md MEMORY.md CONTEXT.md"
  else
    file_list="AGENT.md STATE.md RULES.md MEMORY.md ERRORS.md FILES.md CONTEXT.md"
  fi

  echo -e "  ${CYAN}FILES:${RESET}"
  for f in $file_list; do
    echo "  .claude/$f"
  done
  echo ""

  read -rp "$(echo -e "${BOLD}Proceed? [y/N]:${RESET} ")" confirm
  if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
  fi
  echo ""

  # ── generate ──
  mkdir -p "$CLAUDE_DIR"
  success "Created .claude/"

  generate_agent "$project_name"
  success "Generated AGENT.md"

  generate_state
  success "Generated STATE.md"

  generate_memory
  success "Generated MEMORY.md"

  generate_context
  success "Generated CONTEXT.md"

  if [ "$minimal" = "false" ]; then
    generate_rules
    success "Generated RULES.md"

    generate_errors
    success "Generated ERRORS.md"

    generate_files
    success "Generated FILES.md"
  fi

  # ── .gitignore ──
  if [ -f ".gitignore" ]; then
    if ! grep -q "\.claude/" .gitignore 2>/dev/null; then
      echo "" >> .gitignore
      echo "# claude-init — uncomment to exclude session-specific files" >> .gitignore
      echo "# .claude/ERRORS.md" >> .gitignore
      echo "# .claude/STATE.md" >> .gitignore
    fi
  fi

  # ── done ──
  echo ""
  bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  success "claude-init complete"
  bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo -e "  ${CYAN}NEXT:${RESET} Open Claude and send this:"
  echo ""
  echo -e "  ${BOLD}\"Read everything in .claude/ and give me your Phase 1 briefing.\"${RESET}"
  echo ""
  echo -e "  ${CYAN}LATER:${RESET} End each session with:"
  echo ""
  echo -e "  ${BOLD}claude-init checkpoint${RESET}"
  echo ""
  dim "  github.com/jhaksh-24/claude-init"
  echo ""
}

cmd_checkpoint() {
  if [ ! -d "$CLAUDE_DIR" ]; then
    error "No .claude/ directory found. Run 'claude-init' first."
  fi

  show_banner_mini
  bold "━━━ Session Checkpoint ━━━"
  echo ""

  # ── Phase update ──
  local current_phase
  current_phase=$(grep "^Phase:" "$CLAUDE_DIR/STATE.md" 2>/dev/null | head -1 || echo "unknown")
  info "Current → $current_phase"
  echo ""
  read -rp "$(echo -e "${BOLD}New phase status (or Enter to keep):${RESET} ")" new_phase

  # ── What was completed ──
  echo ""
  read -rp "$(echo -e "${BOLD}What was completed this session?${RESET} ")" completed

  # ── Files changed ──
  local files_changed=""
  local files_rows=""
  echo ""
  read -rp "$(echo -e "${BOLD}Any files created or changed this session? [y/N]:${RESET} ")" has_files
  if [[ "$has_files" =~ ^[Yy]$ ]] && [ -f "$CLAUDE_DIR/FILES.md" ]; then
    echo ""
    echo -e "  ${DIM}Enter each file one at a time. Empty path = done.${RESET}"
    echo -e "  ${DIM}Status: 1=stable  2=wip  3=broken  4=planned${RESET}"
    echo ""
    local file_names_list=""
    while true; do
      read -rp "  $(echo -e "${CYAN}File path${RESET} (or Enter to finish): ")" fpath
      [ -z "$fpath" ] && break
      read -rp "  $(echo -e "${CYAN}Purpose${RESET}: ")" fpurpose
      read -rp "  $(echo -e "${CYAN}Status${RESET} [1-4, default=2]: ")" fstatus_num
      case "${fstatus_num:-2}" in
        1) fstatus="🟢 stable" ;;
        3) fstatus="🔴 broken" ;;
        4) fstatus="⬜ planned" ;;
        *) fstatus="🟡 wip" ;;
      esac
      files_rows+="| ${fpath} | ${fpurpose} | ${fstatus} |\n"
      file_names_list+="${fpath}, "
      echo -e "  ${GREEN}✓${RESET} Logged"
      echo ""
    done
    files_changed="${file_names_list%, }"
  fi

  # ── Decisions ──
  echo ""
  read -rp "$(echo -e "${BOLD}Lock in a decision? [y/N]:${RESET} ")" has_decision
  local decision_block=""
  if [[ "$has_decision" =~ ^[Yy]$ ]]; then
    read -rp "  Decision title: " dtitle
    read -rp "  What was decided: " dwhat
    read -rp "  Why: " dwhy
    decision_block=$(printf "\n### %s\n**Date:** %s\n**Decision:** %s\n**Reason:** %s\n" "$dtitle" "$(today)" "$dwhat" "$dwhy")
  fi

  # ── Errors ──
  echo ""
  read -rp "$(echo -e "${BOLD}Log a bug or mistake? [y/N]:${RESET} ")" has_error
  local error_block=""
  if [[ "$has_error" =~ ^[Yy]$ ]]; then
    read -rp "  Error title: " etitle
    read -rp "  What happened: " ewhat
    read -rp "  Root cause: " ecause
    read -rp "  Fix applied: " efix
    error_block=$(printf "\n### %s\n**Date:** %s\n**What happened:** %s\n**Root cause:** %s\n**Fix applied:** %s\n" "$etitle" "$(today)" "$ewhat" "$ecause" "$efix")
  fi

  # ── Next session ──
  echo ""
  read -rp "$(echo -e "${BOLD}What should next session start with?${RESET} ")" next_task

  # ── Apply updates ──
  echo ""
  info "Saving checkpoint..."

  # Update STATE.md — phase line
  if [ -n "$new_phase" ]; then
    sed_inplace "s/^Phase: .*/Phase: $new_phase/" "$CLAUDE_DIR/STATE.md"
  fi

  # Update STATE.md — metadata
  sed_inplace "s/^Last Updated: .*/Last Updated: $(today)/" "$CLAUDE_DIR/STATE.md"

  # Increment session count
  local count
  count=$(grep "^Session Count:" "$CLAUDE_DIR/STATE.md" | grep -o '[0-9]*' || echo "0")
  local new_count=$((count + 1))
  sed_inplace "s/^Session Count: .*/Session Count: $new_count/" "$CLAUDE_DIR/STATE.md"

  # Update next task
  if [ -n "$next_task" ]; then
    sed_inplace "s/^Next Task: .*/Next Task: $next_task/" "$CLAUDE_DIR/STATE.md"
  fi

  # Update last completed
  if [ -n "$completed" ]; then
    sed_inplace "s/^Last Completed: .*/Last Completed: $completed/" "$CLAUDE_DIR/STATE.md"
  fi

  # Append session log entry
  local log_entry
  log_entry=$(printf "\n### Session %d — %s\n**Completed:** %s\n**Files:** %s\n**Next:** %s\n" \
    "$new_count" "$(today)" "${completed:-nothing}" "${files_changed:-none}" "${next_task:-TBD}")
  echo "$log_entry" >> "$CLAUDE_DIR/STATE.md"
  success "Updated STATE.md"

  # Append decision to MEMORY.md
  if [ -n "$decision_block" ]; then
    echo "$decision_block" >> "$CLAUDE_DIR/MEMORY.md"
    success "Added decision to MEMORY.md"
  fi

  # Append error to ERRORS.md
  if [ -n "$error_block" ]; then
    echo "$error_block" >> "$CLAUDE_DIR/ERRORS.md"
    success "Added error to ERRORS.md"
  fi

  # Write file rows to FILES.md
  if [ -n "$files_rows" ] && [ -f "$CLAUDE_DIR/FILES.md" ]; then
    local files_md="$CLAUDE_DIR/FILES.md"
    # If the table header already exists, insert rows right after the | --- | line
    if grep -q "^| File |" "$files_md" 2>/dev/null; then
      # Find the separator line and append rows after the last table row
      # We do this by appending; markdown tables accept new rows at the end
      printf "%b" "$files_rows" >> "$files_md"
    else
      # No table yet — create header + rows
      printf "\n| File | Purpose | Status |\n|------|---------|--------|\n" >> "$files_md"
      printf "%b" "$files_rows" >> "$files_md"
    fi
    # Timestamped audit trail in RECENT CHANGES
    printf "\n**%s:** %s\n" "$(today)" "$files_changed" >> "$files_md"
    success "Updated FILES.md"
  fi

  echo ""
  bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  success "Checkpoint saved — session $new_count"
  bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  dim "  Next session: \"read .claude/ and tell me current state\""
  echo ""
}

cmd_status() {
  if [ ! -d "$CLAUDE_DIR" ]; then
    error "No .claude/ directory found. Run 'claude-init' first."
  fi

  show_banner_mini

  if [ -f "$CLAUDE_DIR/STATE.md" ]; then
    echo -e "  ${CYAN}STATE${RESET}"
    grep -E "^(Phase:|Last Completed:|Next Task:|Blockers:|Last Updated:|Session Count:|Context Health:)" "$CLAUDE_DIR/STATE.md" 2>/dev/null | while IFS= read -r line; do
      echo -e "  ${DIM}│${RESET} $line"
    done
    echo ""
  fi

  if [ -f "$CLAUDE_DIR/ERRORS.md" ]; then
    local bug_count
    bug_count=$(grep -c "^### " "$CLAUDE_DIR/ERRORS.md" 2>/dev/null | tr -d '\r\n' || echo "0")
    bug_count=${bug_count:-0}
    if [ "$bug_count" -gt 0 ] 2>/dev/null; then
      echo -e "  ${YELLOW}ERRORS${RESET}  $bug_count logged"
    fi
  fi

  if [ -f "$CLAUDE_DIR/MEMORY.md" ]; then
    local decision_count
    decision_count=$(grep -c "^### " "$CLAUDE_DIR/MEMORY.md" 2>/dev/null | tr -d '\r\n' || echo "0")
    decision_count=${decision_count:-0}
    if [ "$decision_count" -gt 0 ] 2>/dev/null; then
      echo -e "  ${GREEN}DECISIONS${RESET}  $decision_count locked"
    fi
  fi

  echo ""
}

# ═══════════════════════════════════════════════════════════════════════════
# REFINE
# ═══════════════════════════════════════════════════════════════════════════

cmd_refine() {
  if [ ! -d "$CLAUDE_DIR" ]; then
    error "No .claude/ directory found. Run 'claude-init' first."
  fi

  show_banner_mini
  bold "━━━ Refine Mode ━━━"
  echo ""
  echo -e "  ${DIM}Analyzes everything that happened in this project${RESET}"
  echo -e "  ${DIM}and generates a prompt to paste into Claude.ai.${RESET}"
  echo -e "  ${DIM}Claude returns specific improvements to each .claude/ file.${RESET}"
  echo ""

  # ── Collect stats ──
  local session_count error_count decision_count file_count
  session_count=$(grep -c "^### Session" "$CLAUDE_DIR/STATE.md" 2>/dev/null | head -1 | tr -d '\r\n ' || echo "0")
  session_count=${session_count:-0}
  error_count=$(grep -c "^### " "$CLAUDE_DIR/ERRORS.md" 2>/dev/null | head -1 | tr -d '\r\n ' || echo "0")
  error_count=${error_count:-0}
  decision_count=$(grep -c "^### " "$CLAUDE_DIR/MEMORY.md" 2>/dev/null | head -1 | tr -d '\r\n ' || echo "0")
  decision_count=${decision_count:-0}
  file_count=$(grep -c "^| " "$CLAUDE_DIR/FILES.md" 2>/dev/null | head -1 | tr -d '\r\n ' || echo "0")
  file_count=${file_count:-0}

  info "Collecting project data..."
  echo -e "  ${DIM}Sessions: $session_count | Errors: $error_count | Decisions: $decision_count | Files: $file_count${RESET}"
  echo ""

  if [ "$session_count" -lt 2 ] 2>/dev/null; then
    warn "Only $session_count session(s) recorded. Refine works best after 3+ sessions."
    echo ""
    read -rp "$(echo -e "${BOLD}Continue anyway? [y/N]:${RESET} ")" cont
    if [[ ! "$cont" =~ ^[Yy]$ ]]; then exit 0; fi
    echo ""
  fi

  # ── Read all .claude/ files ──
  local agent_content state_content memory_content errors_content rules_content files_content
  agent_content=$(cat "$CLAUDE_DIR/AGENT.md" 2>/dev/null || echo "(missing)")
  state_content=$(cat "$CLAUDE_DIR/STATE.md" 2>/dev/null || echo "(missing)")
  memory_content=$(cat "$CLAUDE_DIR/MEMORY.md" 2>/dev/null || echo "(missing)")
  errors_content=$(cat "$CLAUDE_DIR/ERRORS.md" 2>/dev/null || echo "(missing)")
  rules_content=$(cat "$CLAUDE_DIR/RULES.md" 2>/dev/null || echo "(missing)")
  files_content=$(cat "$CLAUDE_DIR/FILES.md" 2>/dev/null || echo "(missing)")

  # ── Build the refine prompt ──
  local prompt_file="$CLAUDE_DIR/REFINE_PROMPT.md"

  {
    echo "# claude-init Refine Request"
    echo ""
    echo "You are analyzing the .claude/ context files of a project to identify"
    echo "specific improvements. These files orient an AI assistant at the start"
    echo "of each session. Suggest concrete, line-level edits based on what actually"
    echo "happened — not generic advice."
    echo ""
    echo "---"
    echo ""
    echo "## PROJECT HISTORY"
    echo ""
    echo "Sessions completed: ${session_count}"
    echo "Errors logged: ${error_count}"
    echo "Decisions locked: ${decision_count}"
    echo "Files tracked: ${file_count}"
    echo ""
    echo "---"
    echo ""
    echo "## CURRENT .claude/ FILES"
    echo ""
    echo "### AGENT.md"
    printf '```\n'
    echo "$agent_content"
    printf '```\n'
    echo ""
    echo "### STATE.md (full session log)"
    printf '```\n'
    echo "$state_content"
    printf '```\n'
    echo ""
    echo "### MEMORY.md"
    printf '```\n'
    echo "$memory_content"
    printf '```\n'
    echo ""
    echo "### ERRORS.md"
    printf '```\n'
    echo "$errors_content"
    printf '```\n'
    echo ""
    echo "### RULES.md"
    printf '```\n'
    echo "$rules_content"
    printf '```\n'
    echo ""
    echo "### FILES.md"
    printf '```\n'
    echo "$files_content"
    printf '```\n'
    echo ""
    echo "---"
    echo ""
    echo "## YOUR TASK"
    echo ""
    echo "Analyze the session log, errors, and decisions. Produce a REFINEMENT REPORT."
    echo "Be specific — quote exact lines, reference what actually happened in sessions."
    echo ""
    echo "### 1. AGENT.md"
    echo "What rules should be added, tightened, or removed?"
    echo "What patterns in the session log show drift from instructions?"
    echo ""
    echo "### 2. RULES.md"
    echo "What red lines were hit or nearly hit? What should be added or cut?"
    echo ""
    echo "### 3. MEMORY.md"
    echo "What decisions should be locked? What belongs in PATTERNS APPROVED/BANNED?"
    echo ""
    echo "### 4. ERRORS.md"
    echo "Any recurring patterns? Prevention rules that are too weak?"
    echo ""
    echo "### 5. CONTEXT.md"
    echo "Any token waste patterns visible in the session log?"
    echo ""
    echo "### 6. Phase structure retrospective"
    echo "Did planned phases match what happened? How would you restructure?"
    echo ""
    echo "### 7. prompt.md improvements"
    echo "What was underspecified and had to be decided mid-project?"
    echo ""
    echo "---"
    echo ""
    echo "Format each suggestion as:"
    echo ""
    echo "> **File:** AGENT.md"
    echo "> **Change:** Add after TOKEN PROTOCOL section"
    echo "> **Add:**"
    echo "> \`\`\`"
    echo "> [exact text]"
    echo "> \`\`\`"
    echo "> **Reason:** [what in the session history motivates this]"
  } > "$prompt_file"

  success "Generated → .claude/REFINE_PROMPT.md"
  echo ""
  bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo -e "  ${CYAN}NEXT STEPS:${RESET}"
  echo ""
  echo -e "  1. Open ${BOLD}.claude/REFINE_PROMPT.md${RESET}"
  echo ""
  echo -e "  2. Paste into ${BOLD}https://claude.ai/new${RESET}"
  echo -e "     ${DIM}Fresh context — don't use an existing conversation${RESET}"
  echo ""
  echo -e "  3. Review suggestions, apply what makes sense"
  echo ""
  echo -e "  4. Run ${BOLD}claude-init ck${RESET} to log the refinement as a session"
  echo ""
  bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""

  # Try to auto-copy to clipboard
  if command -v pbcopy &>/dev/null; then
    pbcopy < "$prompt_file" 2>/dev/null && success "Also copied to clipboard"
  elif command -v xclip &>/dev/null; then
    xclip -selection clipboard < "$prompt_file" 2>/dev/null && success "Also copied to clipboard"
  elif command -v xsel &>/dev/null; then
    xsel --clipboard --input < "$prompt_file" 2>/dev/null && success "Also copied to clipboard"
  elif command -v clip.exe &>/dev/null; then
    clip.exe < "$prompt_file" 2>/dev/null && success "Also copied to clipboard"
  else
    dim "  Tip (WSL): cat .claude/REFINE_PROMPT.md | clip.exe"
  fi
  echo ""
}

# ═══════════════════════════════════════════════════════════════════════════
# ARGUMENT PARSING & DISPATCH
# ═══════════════════════════════════════════════════════════════════════════

COMMAND="init"
MINIMAL=false
FORCE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    checkpoint|ck)  COMMAND="checkpoint"; shift ;;
    status|st)      COMMAND="status"; shift ;;
    refine|rf)      COMMAND="refine"; shift ;;
    --minimal|-m)   MINIMAL=true; shift ;;
    --force|-f)     FORCE=true; shift ;;
    --help|-h)      show_help; exit 0 ;;
    --version|-v)   echo "claude-init v${VERSION}"; exit 0 ;;
    *)              warn "Unknown argument: $1"; show_help; exit 1 ;;
  esac
done

case "$COMMAND" in
  init)       cmd_init "$MINIMAL" "$FORCE" ;;
  checkpoint) cmd_checkpoint ;;
  status)     cmd_status ;;
  refine)     cmd_refine ;;
esac
